// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Recommends the best tool (RSS feed parser, API, etc.) for fetching blog posts from Medium, Hashnode, and Substack.
 *
 * - recommendBlogTool - A function that recommends the best tool for fetching blog posts.
 * - RecommendBlogToolInput - The input type for the recommendBlogTool function.
 * - RecommendBlogToolOutput - The return type for the recommendBlogTool function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendBlogToolInputSchema = z.object({
  platform: z.enum(['Medium', 'Hashnode', 'Substack']).describe('The blogging platform.'),
  numPosts: z.number().min(1).max(10).describe('The number of blog posts to fetch.'),
  tags: z.string().optional().describe('Specific tags to filter blog posts by.'),
  publicationName: z.string().optional().describe('The name of the publication on the platform.'),
});

export type RecommendBlogToolInput = z.infer<typeof RecommendBlogToolInputSchema>;

const RecommendBlogToolOutputSchema = z.object({
  toolRecommendation: z.string().describe('The recommended tool for fetching blog posts (e.g., RSS feed parser, API) along with reasoning.'),
  reasoning: z.string().describe('The reasoning behind the tool recommendation.'),
});

export type RecommendBlogToolOutput = z.infer<typeof RecommendBlogToolOutputSchema>;

export async function recommendBlogTool(input: RecommendBlogToolInput): Promise<RecommendBlogToolOutput> {
  return recommendBlogToolFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendBlogToolPrompt',
  input: {schema: RecommendBlogToolInputSchema},
  output: {schema: RecommendBlogToolOutputSchema},
  prompt: `You are an expert in integrating blog content from various platforms into digital portfolios.
  Given the user's specifications for fetching blog posts from {{platform}}, recommend the best tool (RSS feed parser, API, etc.) and explain your reasoning.

  Specifications:
  - Platform: {{platform}}
  - Number of posts: {{numPosts}}
  {{#if tags}}
  - Tags: {{tags}}
  {{/if}}
  {{#if publicationName}}
  - Publication Name: {{publicationName}}
  {{/if}}

  Tool Recommendation:`, 
});

const recommendBlogToolFlow = ai.defineFlow(
  {
    name: 'recommendBlogToolFlow',
    inputSchema: RecommendBlogToolInputSchema,
    outputSchema: RecommendBlogToolOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
